// <auto-generated />
namespace NewTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New112 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New112));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291631327_New112"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
